# ─────────────────────────────────────────────────────────────────────────────
# Makefile for lob-engine
#
# On Mac, 'make' will use Apple's clang++ automatically.
# On Linux, it uses g++. Both work fine with C++17.
#
# Commands:
#   make          → build the lob_engine binary
#   make clean    → delete build artifacts
#   make run      → build and run with a test ITCH file (if it exists)
# ─────────────────────────────────────────────────────────────────────────────

CXX      := c++
CXXFLAGS := -std=c++17 -O2 -Wall -Wextra -Iinclude -MMD -MP
TARGET   := lob_engine

# All .cpp source files
SOURCES  := src/feed/itch_parser.cpp \
            src/book/order_book.cpp  \
            src/features/feature_engine.cpp \
            src/main.cpp

# Object files go in build/
OBJECTS  := $(SOURCES:src/%.cpp=build/%.o)

# Auto-generated dependency files (one per .o, tracks which headers each .cpp includes)
DEPS     := $(OBJECTS:.o=.d)

# ── Build rules ──────────────────────────────────────────────────────────────

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^
	@echo ""
	@echo "Build successful! Binary: ./$(TARGET)"
	@echo "Usage: ./$(TARGET) <itch_file.bin> <TICKER> <output.csv>"

# Compile each .cpp → .o
build/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf build/ $(TARGET)

# Quick test: parse a sample file if it exists
run: $(TARGET)
	@if [ -f data/sample.bin ]; then \
		./$(TARGET) data/sample.bin AAPL data/features_AAPL.csv; \
	else \
		echo "No data/sample.bin found. Download ITCH data first — see README.md"; \
	fi

# Pull in per-object header dependencies generated by -MMD -MP.
# The leading dash suppresses errors on the first build (before any .d files exist).
-include $(DEPS)

.PHONY: all clean run
