"""
provenance.py — data provenance stamping and load-time verification.

WHY THIS EXISTS: on 2026-07-24 every CSV in data/ was found to have been
generated by a parser version that predated a stock-field byte-alignment fix,
producing a corrupted reconstructed book (see results/OFI_STUDY.md,
"Blocker 1"). Nothing caught this for months because nothing checked which
code version produced a given data file. This module makes that check
automatic and mandatory.

MECHANISM: a sidecar ``<file>.meta`` JSON file next to each generated CSV,
not a header line embedded in the CSV itself and not a hash baked into the
filename.
  - A header line would require every CSV reader (pandas, the C++ engine's
    own tooling, spot-checks with `head`) to know to skip it; pandas'
    ``read_csv`` has no clean "ignore this one line" default that survives
    column-name inference.
  - A hash-in-filename scheme means renaming every consumer path whenever
    the commit changes, and 40-char hex in a filename is unpleasant to work
    with directly.
  - A sidecar file is the standard pattern for this exact problem (think
    ``.sha256`` checksum files): trivial to read, trivial to ignore if you
    don't care, and it can carry more than one field (commit, timestamp,
    source file) without touching the CSV's own format at all.

USAGE:
    from provenance import stamp, verify_provenance

    stamp('data/features_AAPL.csv', ticker='AAPL', source_file='...')
    verify_provenance('data/features_AAPL.csv')   # raises loudly on mismatch
"""

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def _current_commit() -> str:
    """Full HEAD commit hash of this checkout. Raises if not in a git repo."""
    result = subprocess.run(
        ['git', 'rev-parse', 'HEAD'],
        cwd=Path(__file__).resolve().parent.parent,
        capture_output=True, text=True, check=True,
    )
    return result.stdout.strip()


def _meta_path(csv_path) -> Path:
    return Path(str(csv_path) + '.meta')


def stamp(csv_path, ticker: str = None, source_file: str = None) -> Path:
    """Write a provenance sidecar for a just-generated CSV. Call this
    immediately after writing the CSV, from the same process/commit that
    generated it."""
    meta = {
        'generated_by_commit': _current_commit(),
        'generated_at': datetime.now(timezone.utc).isoformat(),
        'ticker': ticker,
        'source_file': source_file,
    }
    meta_path = _meta_path(csv_path)
    meta_path.write_text(json.dumps(meta, indent=2) + '\n')
    return meta_path


class ProvenanceError(RuntimeError):
    """Raised when a data file's provenance stamp is missing or stale.
    This is a hard failure by design — see module docstring."""


def verify_provenance(csv_path) -> None:
    """Verify csv_path's sidecar stamp matches the current HEAD commit.
    Raises ProvenanceError (does NOT warn-and-continue) on any mismatch or
    missing stamp. Callers must not catch this and proceed — a caught and
    ignored ProvenanceError defeats the entire point of this check."""
    meta_path = _meta_path(csv_path)
    if not meta_path.exists():
        raise ProvenanceError(
            f"No provenance stamp for {csv_path} (expected {meta_path}). "
            f"This file's generating commit is unknown — refusing to run. "
            f"Regenerate it via scripts/regenerate_data.sh, which stamps "
            f"its output automatically."
        )

    meta = json.loads(meta_path.read_text())
    stamped_commit = meta.get('generated_by_commit')
    current_commit = _current_commit()

    if stamped_commit != current_commit:
        raise ProvenanceError(
            f"Stale data: {csv_path} was generated by commit "
            f"{stamped_commit}, but HEAD is now {current_commit}. "
            f"The parser/engine code has changed since this file was "
            f"generated — refusing to run analysis on it. Regenerate via "
            f"scripts/regenerate_data.sh."
        )


def _main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='cmd', required=True)

    p_stamp = sub.add_parser('stamp', help='write a provenance sidecar for a CSV')
    p_stamp.add_argument('csv_path')
    p_stamp.add_argument('--ticker', default=None)
    p_stamp.add_argument('--source', default=None, help='raw ITCH file used to generate this CSV')

    p_verify = sub.add_parser('verify', help='verify a CSV against current HEAD')
    p_verify.add_argument('csv_path')

    args = parser.parse_args()

    if args.cmd == 'stamp':
        meta_path = stamp(args.csv_path, ticker=args.ticker, source_file=args.source)
        print(f"Stamped {args.csv_path} -> {meta_path}")
    elif args.cmd == 'verify':
        try:
            verify_provenance(args.csv_path)
            print(f"OK: {args.csv_path} matches current HEAD.")
        except ProvenanceError as e:
            print(f"PROVENANCE CHECK FAILED: {e}")
            sys.exit(1)


if __name__ == '__main__':
    _main()
