#!/usr/bin/env bash
set -euo pipefail

# regenerate_data.sh — one-command regeneration of derived feature CSVs from a
# raw ITCH file: parse -> stamp provenance -> validate the reconstructed book.
#
# WHY THIS EXISTS: on 2026-07-24 every CSV in data/ was found to have been
# silently generated by a stale parser version with a corrupted book
# reconstruction (see results/OFI_STUDY.md, "Blocker 1") — nobody noticed for
# months because nothing stamped which commit produced the data, and nothing
# validated the output automatically. This script makes both checks
# unavoidable. It ALSO defaults to writing to data/staging/, not data/
# directly — a later bug in this exact script overwrote the real (if stale)
# data/features_AAPL.csv with 3 rows of test output while being tested, with
# no backup and no git history to recover from (data/ is gitignored). Staging
# by default means a script bug or a bad raw file can no longer destroy real
# data as a side effect of testing or a mistaken invocation.
#
# Usage:
#   scripts/regenerate_data.sh <raw_itch_file> <TICKER> [<TICKER> ...]
#   scripts/regenerate_data.sh --force <raw_itch_file> <TICKER> [<TICKER> ...]
#
# Default: writes to data/staging/, validates there, and STOPS — nothing in
# data/ is touched. Run scripts/promote_data.sh afterward to publish.
#
# --force: writes directly to data/, skipping staging. Requires explicit
# opt-in on the command line; there is no environment variable or config
# equivalent, specifically so a direct-to-data/ write is always a visible,
# deliberate choice in whatever invoked this.
#
# Example:
#   scripts/regenerate_data.sh data/01302020.NASDAQ_ITCH50 AAPL AMZN ETSY NFLX WDAY
#   scripts/promote_data.sh AAPL AMZN ETSY NFLX WDAY
#
# Requires build_audit/lob_engine to already be built:
#   cmake -DCMAKE_BUILD_TYPE=Release -S . -B build_audit -DCMAKE_PREFIX_PATH=/opt/homebrew
#   cmake --build build_audit -j 8

FORCE=0
if [ "${1:-}" = "--force" ]; then
  FORCE=1
  shift
fi

if [ $# -lt 2 ]; then
  echo "Usage: $0 [--force] <raw_itch_file> <TICKER> [<TICKER> ...]" >&2
  exit 1
fi

ITCH_FILE="$1"
shift
TICKERS=("$@")

if [ ! -f "$ITCH_FILE" ]; then
  echo "Error: $ITCH_FILE not found." >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENGINE="$REPO_ROOT/build_audit/lob_engine"
if [ ! -x "$ENGINE" ]; then
  echo "Error: $ENGINE not built. Run:" >&2
  echo "  cmake -DCMAKE_BUILD_TYPE=Release -S $REPO_ROOT -B $REPO_ROOT/build_audit -DCMAKE_PREFIX_PATH=/opt/homebrew" >&2
  echo "  cmake --build $REPO_ROOT/build_audit -j 8" >&2
  exit 1
fi

if [ "$FORCE" -eq 1 ]; then
  OUT_DIR="$REPO_ROOT/data"
  echo "!! --force: writing directly to $OUT_DIR (bypassing staging) !!"
else
  OUT_DIR="$REPO_ROOT/data/staging"
  echo "Writing to $OUT_DIR (staging only — nothing in data/ will be touched)."
fi
mkdir -p "$OUT_DIR"

OUT_FILES=()

for TICKER in "${TICKERS[@]}"; do
  OUT="$OUT_DIR/features_${TICKER}.csv"
  echo "== Generating $OUT from $ITCH_FILE =="
  "$ENGINE" "$ITCH_FILE" "$TICKER" "$OUT"

  echo "== Stamping provenance =="
  python3 "$REPO_ROOT/scripts/provenance.py" stamp "$OUT" --ticker "$TICKER" --source "$ITCH_FILE"

  OUT_FILES+=("$OUT")
done

echo ""
echo "== Validating reconstructed books (this is what caught the 2026-07-24 bug) =="
python3 "$REPO_ROOT/scripts/validate_book.py" "${OUT_FILES[@]}"
# validate_book.py exits 1 on failure — set -e above means this script stops
# here if validation fails, before anyone downstream trusts the new data.

echo ""
echo "Done. Regenerated and validated: ${OUT_FILES[*]}"
if [ "$FORCE" -eq 0 ]; then
  echo ""
  echo "These files are in staging, NOT data/. To publish them:"
  echo "  scripts/promote_data.sh ${TICKERS[*]}"
fi
echo ""
echo "Note: this regenerates single-day features_<TICKER>.csv files only. To"
echo "rebuild a multi-day panel_<TICKER>.csv, run this once per day's raw ITCH"
echo "file and concatenate the resulting CSVs with a 'date' column added --"
echo "no automated multi-day panel builder exists yet (out of scope of this"
echo "script; the original panel_*.csv provenance/build process is unknown)."
