"""
test_provenance.py — proves scripts/provenance.py fails loudly on stale/missing
stamps, and passes silently when the stamp matches HEAD.

Plain assert-based, no framework — matches this repo's existing test style
(test/test_order_book.cpp). Run: python3 scripts/test_provenance.py
"""

import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from provenance import stamp, verify_provenance, ProvenanceError, _current_commit


def test_correct_stamp_passes():
    with tempfile.TemporaryDirectory() as d:
        csv_path = Path(d) / 'features_TEST.csv'
        csv_path.write_text('ts,mid_price\n1,100.0\n')
        stamp(csv_path, ticker='TEST', source_file='dummy.bin')

        verify_provenance(csv_path)  # must not raise
    print("PASS test_correct_stamp_passes")


def test_missing_stamp_fails_loudly():
    with tempfile.TemporaryDirectory() as d:
        csv_path = Path(d) / 'features_TEST.csv'
        csv_path.write_text('ts,mid_price\n1,100.0\n')
        # No .meta written at all.

        try:
            verify_provenance(csv_path)
            assert False, "expected ProvenanceError for missing stamp, got none"
        except ProvenanceError as e:
            assert str(csv_path) in str(e)
    print("PASS test_missing_stamp_fails_loudly")


def test_mismatched_stamp_fails_loudly_and_names_both_hashes():
    with tempfile.TemporaryDirectory() as d:
        csv_path = Path(d) / 'features_TEST.csv'
        csv_path.write_text('ts,mid_price\n1,100.0\n')

        # Deliberately wrong commit hash — simulates data generated by a
        # since-changed parser version (exactly the 2026-07-24 incident).
        fake_old_commit = '0' * 40
        meta_path = Path(str(csv_path) + '.meta')
        meta_path.write_text(json.dumps({
            'generated_by_commit': fake_old_commit,
            'generated_at': '2020-01-01T00:00:00+00:00',
            'ticker': 'TEST',
            'source_file': 'dummy.bin',
        }))

        real_head = _current_commit()
        assert fake_old_commit != real_head, \
            "test fixture bug: fake hash accidentally matches real HEAD"

        try:
            verify_provenance(csv_path)
            assert False, "expected ProvenanceError for mismatched stamp, got none"
        except ProvenanceError as e:
            msg = str(e)
            # Error must name BOTH hashes, per the requirement that this
            # fail loudly with enough information to diagnose, not just
            # "something's wrong".
            assert fake_old_commit in msg, f"stamped (old) commit missing from error: {msg}"
            assert real_head in msg, f"current HEAD commit missing from error: {msg}"
    print("PASS test_mismatched_stamp_fails_loudly_and_names_both_hashes")


if __name__ == '__main__':
    test_correct_stamp_passes()
    test_missing_stamp_fails_loudly()
    test_mismatched_stamp_fails_loudly_and_names_both_hashes()
    print("\nAll 3 provenance tests passed.")
